### ISSUE TITLE
the map is showing blank

### ISSUE THREAD

**Issue by MelanieMarval** [hemangsk/capacitor-googlemaps-native#16]
![photo_2020-10-02_14-41-27](https://user-images.githubusercontent.com/43726363/94958668-ee672800-04bd-11eb-987f-8e3e09142a7f.jpg)

### This is how the map looks when I run it on android.

I created a totally blank project just to test the map, but no matter how hard I try, it does not display well and does not throw any error.

**This is my .ts**

`
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { Plugins } from '@capacitor/core';
import { CapacitorGoogleMapsPlugin } from 'capacitor-googlemaps-native';

const { CapacitorGoogleMaps } = Plugins;

...
...

    @ViewChild('map', {static: false}) mapView: ElementRef;
    capacitorGoogleMapsPlugin: CapacitorGoogleMapsPlugin = CapacitorGoogleMaps;

    constructor() {
    }

    async ngOnInit() {
        // await this.capacitorGoogleMapsPlugin.initialize({
        //     key: 'AIzaSyD3t5VAdEBMdICcY9FyVcgBHlkeu72OI4',
        // });
    }

    async ionViewDidEnter() {
        const boundingRect = this.mapView.nativeElement.getBoundingClientRect() as DOMRect;

        this.capacitorGoogleMapsPlugin.create({
            width: Math.round(boundingRect.width),
            height: Math.round(boundingRect.height),
            x: Math.round(boundingRect.x),
            y: Math.round(boundingRect.y),
            latitude: -33.86,
            longitude: 151.20,
            zoom: 12,
        });

        this.capacitorGoogleMapsPlugin.addListener('onMapReady', async () => {

            /*
              We can do all the magic here when map is ready
            */

            this.capacitorGoogleMapsPlugin.addMarker({
                latitude: -33.86,
                longitude: 151.20,
                title: 'Custom Title',
                snippet: 'Custom Snippet',
            });

            this.capacitorGoogleMapsPlugin.setMapType({
                type: 'normal',
            });
        });
    }

    ionViewDidLeave() {
        this.capacitorGoogleMapsPlugin.close();
    }

`

**Comment by hemangsk** [comment]
The code you shared looks good. Have you configured the key in AndroidManifest ? https://github.com/hemangsk/capacitor-googlemaps-native#add-api-key-to-your-app

**Comment by MelanieMarval** [comment]
Yes, I do
![image](https://user-images.githubusercontent.com/43726363/94970336-748d6980-04d2-11eb-8864-7cb0a1699804.png)

And add plugin class in MainActivity
![image](https://user-images.githubusercontent.com/43726363/94970408-9be43680-04d2-11eb-83d7-2ef68f12b253.png)

**Comment by hemangsk** [comment]
A few checks I can think of:
- We've to ensure **Maps SDK for Android** is enabled for your API key in Google cloud console.
- Internet access should be available on the device/emulator so that the library can fetch the map tiles. 
- Version of library is 0.0.3 and not an older one.
- Is the below mentioned line showing typescript lint errors?
```
capacitorGoogleMapsPlugin: CapacitorGoogleMapsPlugin = CapacitorGoogleMaps;
```
I'm seeing 
```
Type '{ [prop: string]: any; }' is missing the following properties from type 'CapacitorGoogleMapsPlugin': create, initialize, addMarker, setMapType, and 17 more.ts(2740)
```
But, after changing to 

```
capacitorGoogleMapsPlugin = CapacitorGoogleMaps;
```
it compiles. 


Let me know if that solves the issue. I will try to prep a bare bones demo tomorrow incase we aren't able to figure this out.

**Comment by MelanieMarval** [comment]
Sorry, my mistake, you have activated only the SDK for Javascript and not for android, now that I add it it looks perfectly, thanks for your time and sorry for the inconvenience.

And no, it does not present me with typescript  lint errors

**Comment by hemangsk** [comment]
No worries! I'm glad you got this resolved :)  closing the ticket
