### ISSUE TITLE
enableCurrentLocation doesnt work

### ISSUE THREAD

**Issue by abcoskn** [hemangsk/capacitor-googlemaps-native#21]
when i try to use enableCurrentLocation function, i face a problem on ios platform, 

i have tried in two way to call the function;
`CapacitorGoogleMaps.enableCurrentLocation();`
or
`CapacitorGoogleMaps.enableCurrentLocation({enabled:"true"});`
but both dont work,

you can see the error log below
<img width="478" alt="Ekran Resmi 2021-01-05 16 01 47" src="https://user-images.githubusercontent.com/6419471/103649829-2922a580-4f70-11eb-9443-51d874c8647f.png">

i hope it may be figure out

**Comment by hemangsk** [comment]
Fix is merged thanks to @abcoskn
