### ISSUE TITLE
Ability to get more information than just coordinates from 'didTap' event

### ISSUE THREAD

**Issue by quaz579** [hemangsk/capacitor-googlemaps-native#22]
I'm using the following code to capture events when a user taps on a marker which I'm setting with the "addMarker" method
`CapacitorGoogleMaps.addListener("didTap", (value) => {
      console.log('didTap fired', value.result);
    });`

On ios, the resulting `value` in the function above has the following structure:
`{
result: {
coordinates: {
latitude: number,
longitude: number
}
}
}`

On android, I get an entirely different object in the `value`:
`{
location:{
latitude: number,
longitude: number
},
name: string,
snippet: string
}`

Is there any way to expose information other than just latitude and longitude on both ios and android?  It would also be incredibly useful if we could expose information about the tapped marker beyond just what is visible in the settings as I'd like to act on a unique identifier other than the gps coordinates.  Also curious if the plan is to return a consistent object structure across both ios and android.

**Comment by hemangsk** [comment]
Thanks for the detailed info about the issue!

> Is there any way to expose information other than just latitude and longitude on both iOS and android?

I think there are some modifications needed to get more info like which marker was tapped on, etc. Mainly, that will also require us to add support for assigning an ID or a key to each marker. Marker ID will definitely be an extremely useful addition. 

> Also curious if the plan is to return a consistent object structure across both ios and android.

Yes the plan is to fix it and any other such inconsistencies related to typings. Thanks for bringing this to light, definitely a coding error. I guess it can be a part of a separate patch where we add proper typings for all of the functions.

**Comment by hemangsk** [comment]
@quaz579, fyi the fix is up at https://github.com/hemangsk/capacitor-googlemaps-native/pull/27, it'd be nice if you can give the  PR a review :)

**Comment by quaz579** [comment]
I went ahead and approved this as I didn't see any code smells and it
seemed like a fairly lightweight change.  That said, I do come from a .NET
background primarily so take my approval with a grain of salt.

**Comment by hemangsk** [comment]
Thanks a lot for taking a look!

**Comment by hemangsk** [comment]
Fixed in 0.0.4 🎉

**Comment by quaz579** [comment]
No problem at all.  I was actually curious if you'd be willing to schedule
a 30 minute video conference/screen share session at some point in the
next couple of weeks? I'm interested in potentially contributing to this
project but could use some guidance on getting my development environment
up and running and a brief walkthrough of how this works.

Thanks,
Ben

**Comment by hemangsk** [comment]
@quaz579 Sure, sounds good. What time zone are you in btw? 
feel free to shoot an email at hemangsk@gmail.com
