### ISSUE TITLE
can this plugin work with kml

### ISSUE THREAD

**Issue by TeetawatChitpitak** [hemangsk/capacitor-googlemaps-native#41]
i want to add kml layer to the map.  can this plugin do this thing if can add the layer can i export the map section to kmz file or store whole map section to variable to export by myself

**Comment by hemangsk** [comment]
This feature does not exist yet in the plugin. I'll be glad to assist incase you want to add this.

https://developers.google.com/maps/documentation/android-sdk/utility/kml 
https://developers.google.com/maps/documentation/ios-sdk/utility/kml-geojson

**Comment by TeetawatChitpitak** [comment]
thanks
